### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: 'Intel/neural-chat-7b-v3-1'

### ISSUE THREAD

**Issue by azhuvath** [intel/intel-extension-for-transformers#1175]
**Created a virtual environment using the following commands.**

git clone https://github.com/intel/neural-speed.git
python3 -m venv itrex_env
source itrex_env/bin/activate
cd neural-speed
pip install -r requirements.txt
pip install .
pip install intel-extension-for-transformers intel_extension_for_pytorch accelerate datasets

**Tried executing the sample code given for INT4.**

from transformers import AutoTokenizer, TextStreamer
from intel_extension_for_transformers.transformers import AutoModelForCausalLM
model_name = "Intel/neural-chat-7b-v3-1"     
prompt = "Once upon a time, there existed a little girl,"

tokenizer = AutoTokenizer.from_pretrained(model_name, trust_remote_code=True)
inputs = tokenizer(prompt, return_tensors="pt").input_ids
streamer = TextStreamer(tokenizer)

model = AutoModelForCausalLM.from_pretrained(model_name, load_in_4bit=True)
outputs = model.generate(inputs, streamer=streamer, max_new_tokens=300)

**Getting the following error**

No CUDA runtime is found, using CUDA_HOME='/usr/local/cuda'
2024-01-22 09:42:48 [INFO] cpu device is used.
2024-01-22 09:42:48 [INFO] Applying Weight Only Quantization.
2024-01-22 09:42:48 [INFO] Using LLM runtime.
cmd: ['python', PosixPath('/home/sdp/cerelabs/itrex_env/lib/python3.10/site-packages/neural_speed/convert/convert_mistral.py'), '--outfile', 'runtime_outs/ne_mistral_f32.bin', '--outtype', 'f32', 'Intel/neural-chat-7b-v3-1']
Loading model file Intel/neural-chat-7b-v3-1
Traceback (most recent call last):
  File "/home/sdp/cerelabs/itrex_env/lib/python3.10/site-packages/neural_speed/convert/convert_mistral.py", line 1329, in <module>
    main()
  File "/home/sdp/cerelabs/itrex_env/lib/python3.10/site-packages/neural_speed/convert/convert_mistral.py", line 1309, in main
    model_plus = load_some_model(args.model)
  File "/home/sdp/cerelabs/itrex_env/lib/python3.10/site-packages/neural_speed/convert/convert_mistral.py", line 1221, in load_some_model
    models_plus.append(lazy_load_file(path))
  File "/home/sdp/cerelabs/itrex_env/lib/python3.10/site-packages/neural_speed/convert/convert_mistral.py", line 981, in lazy_load_file
    fp = open(path, 'rb')
FileNotFoundError: [Errno 2] No such file or directory: 'Intel/neural-chat-7b-v3-1'
Traceback (most recent call last):
  File "/home/sdp/cerelabs/neural_chat.py", line 10, in <module>
    model = AutoModelForCausalLM.from_pretrained(model_name, load_in_4bit=True)
  File "/home/sdp/cerelabs/itrex_env/lib/python3.10/site-packages/intel_extension_for_transformers/transformers/modeling/modeling_auto.py", line 331, in from_pretrained
    model.init(
  File "/home/sdp/cerelabs/itrex_env/lib/python3.10/site-packages/neural_speed/__init__.py", line 117, in init
    assert os.path.exists(fp32_bin), "Fail to convert pytorch model"
AssertionError: Fail to convert pytorch model

**Comment by a32543254** [comment]
please download the Intel/neural-chat-7b-v3-1 HF model to local path then put the local path to model name, then you can run the example code

**Comment by azhuvath** [comment]
Downloaded the model using the below code.

from transformers import AutoTokenizer, AutoModelForCausalLM
model_name = "Intel/neural-chat-7b-v3-1"
prompt = "Once upon a time, there existed a little girl,"

tokenizer = AutoTokenizer.from_pretrained(model_name, trust_remote_code=True)
inputs = tokenizer(prompt, return_tensors="pt").input_ids

model = AutoModelForCausalLM.from_pretrained(model_name)

model.save_pretrained(model_name, from_pt=True)
tokenizer.save_pretrained(model_name)
