### ISSUE TITLE
Running Stable Diffusion on IPEX CPU has error

### ISSUE THREAD

**Issue by leopck** [intel/intel-extension-for-transformers#1345]
I'm running using the validated configuration of IPEX CPU IPEX 2.1.0+cpu but it has issues after running your sample:

This is my Dockerfile:

```dockerfile
FROM intel/intel-extension-for-pytorch:2.1.0-pip-base
USER root
SHELL ["/bin/bash", "-o", "pipefail", "-c"]

COPY ./intel-extension-for-transformers/examples/huggingface/pytorch/text-to-image/deployment/stable_diffusion/requirements.txt ./sd/requirements.txt
RUN cd sd && \
    pip install -r requirements.txt transformers==4.34.1 diffusers==0.12.1

RUN pip install intel-extension-for-transformers
COPY ./intel-extension-for-transformers/examples/huggingface/pytorch/text-to-image/deployment/stable_diffusion ./sd

```

```
# python prepare_model.py --input_model=CompVis/stable-diffusion-v1-4 --output_path=./model
# bash export_model.sh --input_model=model --precision=fp32
# python run_executor.py --ir_path=./fp32_ir --input_model=CompVis/stable-diffusion-v1-4
Traceback (most recent call last):
  File "/inpainting/run_executor.py", line 236, in <module>
    main()
  File "/inpainting/run_executor.py", line 157, in main
    neural_engine_graph = diffusion_utils.neural_engine_init(args.ir_path)
  File "/inpainting/diffusion_utils.py", line 666, in neural_engine_init
    text_encoder_graph.graph_init(text_encoder_conf, text_encoder_bin)
  File "/usr/local/lib/python3.10/dist-packages/intel_extension_for_transformers/llm/runtime/deprecated/compile/graph/graph.py", line 680, in graph_init
    tensor = tensor_name_2_class[tensor_name]
KeyError: '/text_model/Gather_1_output_0:0'
```

**Comment by Zhenzhong1** [comment]
@leopck Hi, please check this https://github.com/intel/intel-extension-for-transformers/issues/78 issue. same problem.

**Comment by leopck** [comment]
> @leopck Hi, please check this #78 issue. same problem.

actually i was not using your latest code from `main` branch but rather, i was using your release branch with your release pip wheel that was validated against the IPEX version using the release SD version but it's okay I resolved the issue using all latest version instead.
