### ISSUE TITLE
Unsupported GPU device: Intel(R) UHD Graphics 770 in version 1.4

### ISSUE THREAD

**Issue by fakezeta** [intel/intel-extension-for-transformers#1463]
Hi, 

with 
```
intel-extension-for-pytorch      2.1.10+xpu
intel-extension-for-transformers 1.4
oneapi                           2024.0
```
```
Python 3.10.12 (main, Nov 20 2023, 15:14:05) [GCC 11.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from intel_extension_for_transformers.transformers.modeling import AutoModelForCausalLM
2024-04-08 13:53:53,822 - datasets - INFO - PyTorch version 2.1.0a0+cxx11.abi available.
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.10/dist-packages/intel_extension_for_transformers/transformers/__init__.py", line 56, in <module>
    from .modeling import (
  File "/usr/local/lib/python3.10/dist-packages/intel_extension_for_transformers/transformers/modeling/__init__.py", line 22, in <module>
    from .modeling_auto import (AutoModel, AutoModelForCausalLM,
  File "/usr/local/lib/python3.10/dist-packages/intel_extension_for_transformers/transformers/modeling/modeling_auto.py", line 87, in <module>
    if is_ipex_available() and get_gpu_family() != "no_gpu":
  File "/usr/local/lib/python3.10/dist-packages/intel_extension_for_transformers/tools/utils.py", line 63, in get_gpu_family
    assert False, "Unsupported GPU device: {}".format(name)
AssertionError: Unsupported GPU device: Intel(R) UHD Graphics 770
>>> from intel_extension_for_transformers.transformers import AutoModelForCausalLM
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.10/dist-packages/intel_extension_for_transformers/transformers/__init__.py", line 56, in <module>
    from .modeling import (
  File "/usr/local/lib/python3.10/dist-packages/intel_extension_for_transformers/transformers/modeling/__init__.py", line 22, in <module>
    from .modeling_auto import (AutoModel, AutoModelForCausalLM,
  File "/usr/local/lib/python3.10/dist-packages/intel_extension_for_transformers/transformers/modeling/modeling_auto.py", line 87, in <module>
    if is_ipex_available() and get_gpu_family() != "no_gpu":
  File "/usr/local/lib/python3.10/dist-packages/intel_extension_for_transformers/tools/utils.py", line 63, in get_gpu_family
    assert False, "Unsupported GPU device: {}".format(name)
AssertionError: Unsupported GPU device: Intel(R) UHD Graphics 770
```

No error with 
```
intel-extension-for-pytorch      2.1.10+xpu
intel-extension-for-transformers 1.3.2
oneapi                           2024.0
```

**Comment by kevinintel** [comment]
Hi fakezeta,
we did not support old iGPU, please use new iGPU.

**Comment by fakezeta** [comment]
thank you, gonna close the issue
