### ISSUE TITLE
unable to start talkingbot frondend

### ISSUE THREAD

**Issue by raj-ritu17** [intel/intel-extension-for-transformers#1517]
**followed the guidelines mentioned here:** 

https://github.com/intel/intel-extension-for-transformers/tree/main/intel_extension_for_transformers/neural_chat/ui/customized/talkingbot

process failed during dependencies 

```
npm WARN deprecated @types/sass@1.45.0: This is a stub types definition. sass provides its own type definitions, so you do not need this installed.
npm WARN deprecated minimatch@0.0.5: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated sourcemap-codec@1.4.8: Please use @jridgewell/sourcemap-codec instead
npm ERR! code 1
npm ERR! path /home/intel/ritu/talkingBot/intel-extension-for-transformers/intel_extension_for_transformers/neural_chat/ui/customized/talkingbot/node_modules/@sveltejs/kit
npm ERR! command failed
npm ERR! command sh -c node postinstall.js
npm ERR! file:///home/intel/ritu/talkingBot/intel-extension-for-transformers/intel_extension_for_transformers/neural_chat/ui/customized/talkingbot/node_modules/@sveltejs/kit/postinstall.js:7
npm ERR!        const cwd = process.env.INIT_CWD ?? process.cwd();
npm ERR!                                          ^
npm ERR!
npm ERR! SyntaxError: Unexpected token '?'
npm ERR!     at Loader.moduleStrategy (internal/modules/esm/translators.js:133:18)
npm ERR!     at async link (internal/modules/esm/module_job.js:42:21)

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/intel/.npm/_logs/2024-04-26T07_31_20_839Z-debug-0.log
```

**Comment by WenjiaoYue** [comment]
Hi, could you please confirm your node version? I'm using the latest node [node: v20.11.1, npm: 10.1.0], and it runs smoothly. It seems the issue might be due to version incompatibility. Would you consider upgrading your node version to see if the problem persists? Versions 18 and above should all be compatible.

**Comment by raj-ritu17** [comment]
@WenjiaoYue, upgrading the npm version solve dependency problem.
Now, I have started the server, but it doesn't start any communication.
For example, I am using the default template and starting the voice record but it doesn't return any response.

**npm version:**
![image](https://github.com/intel/intel-extension-for-transformers/assets/110594625/24dc2404-d63f-4eb5-b845-6f83fbed8f59)


![image](https://github.com/intel/intel-extension-for-transformers/assets/110594625/8d946c7c-c2c3-46f7-b6ea-75e16563be30)


**server output:**

```
 1:10:12 PM [vite-plugin-svelte] /home/intel/ritu/talkingBot/intel-extension-for-transformers/intel_extension_for_transformers/neural_chat/ui/customized/talkingbot/src/lib/components/talkbot/bot-template-card.svelte:26:11 Bot_template_card has unused export property 'knowledge'. If it is for external reference only, please consider using `export const knowledge`
8/3/2023 --- CollectionType {
  '0': 'Custom',
  '1': 'Library',
  '2': 'TemplateCustom',
  '3': 'TemplateLibrary',
  Custom: 0,
  Library: 1,
  TemplateCustom: 2,
  TemplateLibrary: 3
} 0

╭── 🌼 daisyUI 3.9.4 https://daisyui.com
│
├── 2 themes are enabled. How to add more themes:
│   https://daisyui.com/docs/themes
│
╰── ⭐️ Star daisyUI project on GitHub: https://github.com/saadeghi/daisyui

1:10:19 PM [vite-plugin-svelte] /home/intel/ritu/talkingBot/intel-extension-for-transformers/intel_extension_for_transformers/neural_chat/ui/customized/talkingbot/src/lib/components/talkbot/bot-template-card.svelte:26:11 Bot_template_card has unused export property 'knowledge'. If it is for external reference only, please consider using `export const knowledge`
1:10:19 PM [vite] ✨ new dependencies optimized: svelte-notifications
1:10:19 PM [vite] ✨ optimized dependencies changed. reloading
1:10:20 PM [vite-plugin-svelte] /home/intel/ritu/talkingBot/intel-extension-for-transformers/intel_extension_for_transformers/neural_chat/ui/customized/talkingbot/src/lib/components/talkbot/bot-template-card.svelte:26:11 Bot_template_card has unused export property 'knowledge'. If it is for external reference only, please consider using `export const knowledge`
1:10:20 PM [vite-plugin-svelte] /home/intel/ritu/talkingBot/intel-extension-for-transformers/intel_extension_for_transformers/neural_chat/ui/customized/talkingbot/src/lib/components/talkbot/bot-template-card.svelte:26:11 Bot_template_card has unused export property 'knowledge'. If it is for external reference only, please consider using `export const knowledge`
8/3/2023 --- CollectionType {
  '0': 'Custom',
  '1': 'Library',
  '2': 'TemplateCustom',
  '3': 'TemplateLibrary',
  Custom: 0,
  Library: 1,
  TemplateCustom: 2,
  TemplateLibrary: 3
} 0
1:10:57 PM [vite-plugin-svelte] /home/intel/ritu/talkingBot/intel-extension-for-transformers/intel_extension_for_transformers/neural_chat/ui/customized/talkingbot/src/lib/modules/chat/chat-message.svelte:83:1 Unused CSS selector "audio::-webkit-media-controls-panel"
1:10:57 PM [vite-plugin-svelte] /home/intel/ritu/talkingBot/intel-extension-for-transformers/intel_extension_for_transformers/neural_chat/ui/customized/talkingbot/src/lib/modules/chat/chat-audio.svelte:23:11 Chat_audio has unused export property 'right'. If it is for external reference only, please consider using `export const right`
1:10:57 PM [vite] ✨ new dependencies optimized: sse.js, nanoid
1:10:57 PM [vite] ✨ optimized dependencies changed. reloading
1:10:58 PM [vite-plugin-svelte] /home/intel/ritu/talkingBot/intel-extension-for-transformers/intel_extension_for_transformers/neural_chat/ui/customized/talkingbot/src/lib/components/talkbot/bot-template-card.svelte:26:11 Bot_template_card has unused export property 'knowledge'. If it is for external reference only, please consider using `export const knowledge`
1:10:58 PM [vite-plugin-svelte] /home/intel/ritu/talkingBot/intel-extension-for-transformers/intel_extension_for_transformers/neural_chat/ui/customized/talkingbot/src/lib/modules/chat/chat-message.svelte:83:1 Unused CSS selector "audio::-webkit-media-controls-panel"
1:10:58 PM [vite-plugin-svelte] /home/intel/ritu/talkingBot/intel-extension-for-transformers/intel_extension_for_transformers/neural_chat/ui/customized/talkingbot/src/lib/modules/chat/chat-audio.svelte:23:11 Chat_audio has unused export property 'right'. If it is for external reference only, please consider using `export const right`
8/3/2023 --- CollectionType {
  '0': 'Custom',
  '1': 'Library',
  '2': 'TemplateCustom',
  '3': 'TemplateLibrary',
  Custom: 0,
  Library: 1,
  TemplateCustom: 2,
  TemplateLibrary: 3
} 0
1:11:03 PM [vite-plugin-svelte] /home/intel/ritu/talkingBot/intel-extension-for-transformers/intel_extension_for_transformers/neural_chat/ui/customized/talkingbot/src/lib/components/talkbot/bot-template-card.svelte:26:11 Bot_template_card has unused export property 'knowledge'. If it is for external reference only, please consider using `export const knowledge`
```

**Comment by WenjiaoYue** [comment]
Now it works fine. The reason for the unresponsive was that browsers only allow microphone and camera access on HTTPS websites by default. You can add the current IP to the "Insecure origins treated as secure" list. After reloading, the browser will prompt to allow microphone access.  
https://stackoverflow.com/questions/52759992/how-to-access-camera-and-microphone-in-chrome-without-https
![image](https://github.com/intel/intel-extension-for-transformers/assets/108783334/89b676ef-c507-4dec-9cfc-4e0e3417df48)

**Comment by WenjiaoYue** [comment]
It looks like there might be some issues with the backend return values. Maybe Liang could help you confirm.
