### ISSUE TITLE
Installation of version1.0b0 via pip fails

### ISSUE THREAD

**Issue by mirix** [intel/intel-extension-for-transformers#50]
Installation of the default version1.0b0 with pip fails with the following error:

```
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-install-836hiul0/intel-extension-for-transformers_bf12f96abdef43088691034a0720ecc9/setup.py", line 185, in <module>
          check_submodules()
        File "/tmp/pip-install-836hiul0/intel-extension-for-transformers_bf12f96abdef43088691034a0720ecc9/setup.py", line 162, in check_submodules
          with open(git_modules_path) as f:
      FileNotFoundError: [Errno 2] No such file or directory: '/tmp/pip-install-836hiul0/intel-extension-for-transformers_bf12f96abdef43088691034a0720ecc9/.gitmodules'

```

However, installing the previous release works:

pip install intel-extension-for-transformers==1.0a0

**Comment by kevinintel** [comment]
Hi, please try latest version.

**Comment by kevinintel** [comment]
hi mirix, please try our latest version
