### ISSUE TITLE
Docker image please

### ISSUE THREAD

**Issue by dataplayer12** [intel/intel-extension-for-transformers#75]
I'm trying to run your code from README on a Xeon Gold 5218R and it gives an error about openGL for some reason. Can you provide a docker image which works with this extension?

**Comment by kevinintel** [comment]
windows or linux?

**Comment by kevinintel** [comment]
can you share the error messages?

**Comment by dataplayer12** [comment]
I managed to get rid of the earlier reported libGL error by installing ffmpeg but another error crops up. Here is the Dockerfile

```Dockerfile
FROM ubuntu:jammy
RUN apt-get update
RUN apt-get upgrade
RUN apt-get install -y python3-dev python3-pip nano
RUN apt-get install -y ffmpeg libsm6
RUN apt-get install -y python3.10-venv
RUN cd /
RUN python3 -m venv .itt
ENV VIRTUAL_ENV=.itt
RUN python3 -m venv $VIRTUAL_ENV
ENV PATH="$VIRTUAL_ENV/bin:$PATH"

RUN python3 -m pip install torch --index-url https://download.pytorch.org/whl/cpu
RUN python3 -m pip install transformers datasets
RUN python3 -m pip install intel-extension-for-transformers
```

- Build this with `docker build -t itt:latest .`
- Run the container with `docker run -it itt:latest bash`
- Copy the two blocks of code from this repo's README into a python script, called, say, `intelkit.py`
- `source /.itt/bin/activate`
- `python3 intelkit.py`

I get this error

```Shell
jaiyam@RRJPHIRANOTP03:~/intel_tf$ sudo docker run -it -v /home/jaiyam/intel_tf/:/intel_tf itt:latest bash
root@2b42b3237890:/# cd /intel_tf/
root@2b42b3237890:/intel_tf# python3 intelkit.py
Traceback (most recent call last):
  File "/intel_tf/intelkit.py", line 1, in <module>
    from datasets import load_dataset, load_metric
ModuleNotFoundError: No module named 'datasets'
root@2b42b3237890:/intel_tf# deactivate
bash: deactivate: command not found
root@2b42b3237890:/intel_tf# source /.itt/bin/activate
(.itt) root@2b42b3237890:/intel_tf# python3 intelkit.py
Downloading builder script: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 28.8k/28.8k [00:00<00:00, 23.1MB/s]
Downloading metadata: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 28.7k/28.7k [00:00<00:00, 16.1MB/s]
Downloading readme: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 27.9k/27.9k [00:00<00:00, 16.4MB/s]
Downloading and preparing dataset glue/sst2 to /root/.cache/huggingface/datasets/glue/sst2/1.0.0/dacbe3125aa31d7f70367a07a8a9e72a5a0bfeb5fc42e75c9db75b96da6053ad...
Downloading data: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 7.44M/7.44M [00:00<00:00, 67.4MB/s]
Dataset glue downloaded and prepared to /root/.cache/huggingface/datasets/glue/sst2/1.0.0/dacbe3125aa31d7f70367a07a8a9e72a5a0bfeb5fc42e75c9db75b96da6053ad. Subsequent calls will reuse this data.
100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 3/3 [00:00<00:00, 991.40it/s]
Downloading (…)okenizer_config.json: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 48.0/48.0 [00:00<00:00, 116kB/s]
Downloading (…)lve/main/config.json: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 629/629 [00:00<00:00, 1.62MB/s]
Downloading (…)solve/main/vocab.txt: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 232k/232k [00:00<00:00, 798kB/s]
Traceback (most recent call last):
  File "/intel_tf/intelkit.py", line 8, in <module>
    from intel_extension_for_transformers.optimization import QuantizationConfig, metrics, objectives
  File "/.itt/lib/python3.10/site-packages/intel_extension_for_transformers/optimization/__init__.py", line 19, in <module>
    from .config import (
  File "/.itt/lib/python3.10/site-packages/intel_extension_for_transformers/optimization/config.py", line 22, in <module>
    from neural_compressor.conf.config import (
ModuleNotFoundError: No module named 'neural_compressor'
```

**Comment by dataplayer12** [comment]
@kevinintel is this information enough for you to reproduce the error?

**Comment by kevinintel** [comment]
You didn't install componenets of requirements.txt
unofficial docker: https://github.com/intel/intel-extension-for-transformers/tree/main/docker

**Comment by dataplayer12** [comment]
Thanks! That worked. One small comment is that I could not pull `intel/ai-tools:itrex-0.1.1` and the other image. Perhaps thats because the images are still private. Other than that, I consider the issue resolved.
